### PR TITLE
Add Skyblock Features to crash data 🥳

### PR DESCRIPTION
**Pull request by RayDeeUx**
Refer to: ModMalwareInvestigation/SkyBlockModWiki#14

### CODE REVIEW

**Comment by Wyvest** [comment]
Personally against disapproving of mods, especially if they're not a RAT, paid, or a mod that actually causes bugs and performance issues. I do see the controversy though, so will see what others think

**Comment by Ascynx** [comment]
I agree with Wyvest,
it might have overlaps (mainly because stuff's copy pasted and all) but if you want to add something like that you'd at least need to pinpoint the possible issues instead.
Because just saying it overlaps isn't exactly a valid reason.

**Comment by RayDeeUx** [comment]
> you'd at least need to pinpoint the possible issues instead. Because just saying it overlaps isn't exactly a valid reason.

From the last time I used it (and after reporting these incompatibilities):
\- teleport overlay directly conflicts with neu aotv etherwarp
\- sidebar settings conflict with vanillahud
\- whatever this is (focusing more on the overlap with neu inventory buttons):


i could keep going later this weekend if you'd like, i just need to load the lastest SBF version onto my 103(!!) prism launcher instance and mess around

**Comment by Wyvest** [comment]
> Personally against disapproving of mods, especially if they're not a RAT, paid, or a mod that actually causes bugs and performance issues. I do see the controversy though, so will see what others think

Actually, I take that back; most of this drama is from directly ripping off code, and we really shouldn't be supporting that in any shape or form.

**Pull request closed without merging**
