### PR TITLE
rayless fearmongering moment + more edits

### PR DESCRIPTION
**Pull request by RayDeeUx**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
if you don’t want to name it then don’t even include that section??? just leave it at no longer maintained

**Comment by RayDeeUx** [comment]
@MicrocontrollersDev done, @nacrt merge when ready

**Comment by nacrt** [comment]
Great pr, but replace ` with %pathindicator% on line 17

**Comment by RayDeeUx** [comment]
@nacrt

**Pull request merged**
